(function(){/*
 *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
*****************************************************************************/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(g){var b=0;return function(){return b<g.length?{done:!1,value:g[b++]}:{done:!0}}};$jscomp.arrayIterator=function(g){return{next:$jscomp.arrayIteratorImpl(g)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,b,d){if(g==Array.prototype||g==Object.prototype)return g;g[b]=d.value;return g};$jscomp.getGlobal=function(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<g.length;++b){var d=g[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(g,b,d){if(!d||null!=g){d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return g[b];d=g[d];return void 0!==d?d:g[b]}};
$jscomp.polyfill=function(g,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(g,b,d,c):$jscomp.polyfillUnisolated(g,b,d,c))};$jscomp.polyfillUnisolated=function(g,b,d,c){d=$jscomp.global;g=g.split(".");for(c=0;c<g.length-1;c++){var e=g[c];if(!(e in d))return;d=d[e]}g=g[g.length-1];c=d[g];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,g,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(g,b,d,c){var e=g.split(".");g=1===e.length;c=e[0];c=!g&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<e.length-1;k++){var a=e[k];if(!(a in c))return;c=c[a]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[e]:null;b=b(d);null!=b&&(g?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+d+"$"+e),$jscomp.defineProperty(c,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(g){if(g)return g;var b=function(k,a){this.$jscomp$symbol$id_=k;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:a})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",c=0,e=function(k){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(d+(k||"")+"_"+c++,k)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(g){if(g)return g;g=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var c=$jscomp.global[b[d]];"function"===typeof c&&"function"!=typeof c.prototype[g]&&$jscomp.defineProperty(c.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return g},"es6",
"es3");$jscomp.iteratorPrototype=function(g){g={next:g};g[Symbol.iterator]=function(){return this};return g};$jscomp.checkEs6ConformanceViaProxy=function(){try{var g={},b=Object.create(new $jscomp.global.Proxy(g,{get:function(d,c,e){return d==g&&"q"==c&&e==b}}));return!0===b.q}catch(d){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.makeIterator=function(g){var b="undefined"!=typeof Symbol&&Symbol.iterator&&g[Symbol.iterator];if(b)return b.call(g);if("number"==typeof g.length)return $jscomp.arrayIterator(g);throw Error(String(g)+" is not an iterable or ArrayLike");};$jscomp.owns=function(g,b){return Object.prototype.hasOwnProperty.call(g,b)};$jscomp.MapEntry=function(){};
$jscomp.polyfill("Promise",function(g){function b(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(f,h){f(a)})}if(g&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return g;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(a)};
var c=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){c(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var f=0;f<a.length;++f){var h=a[f];a[f]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var f=this.createResolveAndReject_();
try{a(f.resolve,f.reject)}catch(h){f.reject(h)}};e.prototype.createResolveAndReject_=function(){function a(l){return function(r){h||(h=!0,l.call(f,r))}}var f=this,h=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var f=null!=a;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(a):
this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var f=void 0;try{f=a.then}catch(h){this.reject_(h);return}"function"==typeof f?this.settleSameAsThenable_(f,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,f){if(0!=this.state_)throw Error("Cannot settle("+a+", "+f+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=f;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var a=this;c(function(){if(a.notifyUnhandledRejection_()){var f=$jscomp.global.console;"undefined"!==typeof f&&f.error(a.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var a=$jscomp.global.CustomEvent,f=$jscomp.global.Event,h=$jscomp.global.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof a?a=new a("unhandledrejection",{cancelable:!0}):
"function"===typeof f?a=new f("unhandledrejection",{cancelable:!0}):(a=$jscomp.global.document.createEvent("CustomEvent"),a.initCustomEvent("unhandledrejection",!1,!0,a));a.promise=this;a.reason=this.result_;return h(a)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new b;e.prototype.settleSameAsPromise_=function(a){var f=this.createResolveAndReject_();
a.callWhenSettled_(f.resolve,f.reject)};e.prototype.settleSameAsThenable_=function(a,f){var h=this.createResolveAndReject_();try{a.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};e.prototype.then=function(a,f){function h(n,w){return"function"==typeof n?function(m){try{l(n(m))}catch(x){r(x)}}:w}var l,r,u=new e(function(n,w){l=n;r=w});this.callWhenSettled_(h(a,l),h(f,r));return u};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,f){function h(){switch(l.state_){case 1:a(l.result_);
break;case 2:f(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(h):this.onSettledCallbacks_.push(h);this.isRejectionHandled_=!0};e.resolve=d;e.reject=function(a){return new e(function(f,h){h(a)})};e.race=function(a){return new e(function(f,h){for(var l=$jscomp.makeIterator(a),r=l.next();!r.done;r=l.next())d(r.value).callWhenSettled_(f,h)})};e.all=function(a){var f=$jscomp.makeIterator(a),h=f.next();return h.done?d([]):new e(function(l,
r){function u(m){return function(x){n[m]=x;w--;0==w&&l(n)}}var n=[],w=0;do n.push(void 0),w++,d(h.value).callWhenSettled_(u(n.length-1),r),h=f.next();while(!h.done)})};return e},"es6","es3");$jscomp.checkStringArgs=function(g,b,d){if(null==g)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return g+""};
$jscomp.polyfill("String.prototype.endsWith",function(g){return g?g:function(b,d){var c=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===d&&(d=c.length);d=Math.max(0,Math.min(d|0,c.length));for(var e=b.length;0<e&&0<d;)if(c[--d]!=b[--e])return!1;return 0>=e}},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var g={a:!0},b={};try{return b.__proto__=g,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(g,b){g.__proto__=b;if(g.__proto__!==b)throw new TypeError(g+" is not extensible");return g}:null;$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(g,b){for(var d=1;d<arguments.length;d++){var c=arguments[d];if(c)for(var e in c)$jscomp.owns(c,e)&&(g[e]=c[e])}return g};
$jscomp.polyfill("Array.from",function(g){return g?g:function(b,d,c){d=null!=d?d:function(f){return f};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var a=0;!(k=b.next()).done;)e.push(d.call(c,k.value,a++))}else for(k=b.length,a=0;a<k;a++)e.push(d.call(c,b[a],a));return e}},"es6","es3");
(function(g){function b(c){if(d[c])return d[c].exports;var e=d[c]={i:c,l:!1,exports:{}};g[c].call(e.exports,e,e.exports,b);e.l=!0;return e.exports}var d={};b.m=g;b.c=d;b.d=function(c,e,k){b.o(c,e)||Object.defineProperty(c,e,{enumerable:!0,get:k})};b.r=function(c){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(c,Symbol.toStringTag,{value:"Module"});Object.defineProperty(c,"__esModule",{value:!0})};b.t=function(c,e){e&1&&(c=b(c));if(e&8||e&4&&"object"===typeof c&&c&&c.__esModule)return c;
var k=Object.create(null);b.r(k);Object.defineProperty(k,"default",{enumerable:!0,value:c});if(e&2&&"string"!=typeof c)for(var a in c)b.d(k,a,function(f){return c[f]}.bind(null,a));return k};b.n=function(c){var e=c&&c.__esModule?function(){return c["default"]}:function(){return c};b.d(e,"a",e);return e};b.o=function(c,e){return Object.prototype.hasOwnProperty.call(c,e)};b.p="/core/officeEditor";return b(b.s=9)})([function(g,b,d){d.d(b,"b",function(){return e});d.d(b,"a",function(){return k});var c=
d(1),e=function(a,f){Object(c.a)("disableLogs")||(f?console.warn(a+": "+f):console.warn(a))},k=function(a,f){}},function(g,b,d){d.d(b,"a",function(){return k});d.d(b,"b",function(){return a});var c={},e={flattenedResources:!1,CANVAS_CACHE_SIZE:void 0,maxPagesBefore:void 0,maxPagesAhead:void 0,disableLogs:!1,wvsQueryParameters:{},_trnDebugMode:!1,_logFiltersEnabled:null},k=function(f){return e[f]},a=function(f,h){var l;e[f]=h;null===(l=c[f])||void 0===l?void 0:l.forEach(function(r){r(h)})}},function(g,
b,d){d.d(b,"a",function(){return A});d.d(b,"b",function(){return H});d.d(b,"c",function(){return I});var c=d(6),e=d(0),k=d(4),a=d(3),f="undefined"===typeof window?self:window,h=f.importScripts,l=!1,r=function(p,q){l||(h(f.basePath+"decode.min.js"),l=!0);p=self.BrotliDecode(Object(a.b)(p));return q?p:Object(a.a)(p)},u=function(p,q){return Object(c.a)(void 0,void 0,Promise,function(){var t;return Object(c.b)(this,function(v){switch(v.label){case 0:return l?[3,2]:[4,Object(k.a)(self.Core.getWorkerPath()+
"external/decode.min.js","Failed to download decode.min.js",window)];case 1:v.sent(),l=!0,v.label=2;case 2:return t=self.BrotliDecode(Object(a.b)(p)),[2,q?t:Object(a.a)(t)]}})})};(function(){function p(){this.remainingDataArrays=[]}p.prototype.processRaw=function(q){return q};p.prototype.processBrotli=function(q){this.remainingDataArrays.push(q);return null};p.prototype.GetNextChunk=function(q){this.decodeFunction||(this.decodeFunction=0===q[0]&&97===q[1]&&115===q[2]&&109===q[3]?this.processRaw:this.processBrotli);
return this.decodeFunction(q)};p.prototype.End=function(){if(this.remainingDataArrays.length){for(var q=this.arrays,t=0,v=0;v<q.length;++v)t+=q[v].length;t=new Uint8Array(t);var y=0;for(v=0;v<q.length;++v){var B=q[v];t.set(B,y);y+=B.length}return r(t,!0)}return null};return p})();var n=!1,w=function(p){n||(h(f.basePath+"pako_inflate.min.js"),n=!0);var q=10;if("string"===typeof p){if(p.charCodeAt(3)&8){for(;0!==p.charCodeAt(q);++q);++q}}else if(p[3]&8){for(;0!==p[q];++q);++q}p=Object(a.b)(p);p=p.subarray(q,
p.length-8);return f.pako.inflate(p,{windowBits:-15})},m=function(p,q){return q?p:Object(a.a)(p)},x=function(p){var q=!p.shouldOutputArray,t=new XMLHttpRequest;t.open("GET",p.url,p.isAsync);var v=q&&t.overrideMimeType;t.responseType=v?"text":"arraybuffer";v&&t.overrideMimeType("text/plain; charset=x-user-defined");t.send();var y=function(){var C=Date.now();var z=v?t.responseText:new Uint8Array(t.response);Object(e.a)("worker","Result length is "+z.length);z.length<p.compressedMaximum?(z=p.decompressFunction(z,
p.shouldOutputArray),Object(e.b)("There may be some degradation of performance. Your server has not been configured to serve .gz. and .br. files with the expected Content-Encoding. See https://docs.apryse.com/documentation/web/faq/content-encoding/ for instructions on how to resolve this."),h&&Object(e.a)("worker","Decompressed length is "+z.length)):q&&(z=Object(a.a)(z));h&&Object(e.a)("worker",p.url+" Decompression took "+(Date.now()-C));return z};if(p.isAsync)var B=new Promise(function(C,z){t.onload=
function(){200===this.status||0===this.status?C(y()):z("Download Failed "+p.url)};t.onerror=function(){z("Network error occurred "+p.url)}});else{if(200===t.status||0===t.status)return y();throw Error("Failed to load "+p.url);}return B},A=function(p){var q=p.lastIndexOf("/");-1===q&&(q=0);var t=p.slice(q).replace(".",".br.");h||(t.endsWith(".js.mem")?t=t.replace(".js.mem",".mem"):t.endsWith(".js")&&(t=t.concat(".mem")));return p.slice(0,q)+t},D=function(p,q){var t=p.lastIndexOf("/");-1===t&&(t=0);
var v=p.slice(t).replace(".",".gz.");q.url=p.slice(0,t)+v;q.decompressFunction=w;return x(q)},E=function(p,q){q.url=A(p);q.decompressFunction=h?r:u;return x(q)},F=function(p,q){p.endsWith(".js.mem")?p=p.slice(0,-4):p.endsWith(".mem")&&(p=p.slice(0,-4)+".js.mem");q.url=p;q.decompressFunction=m;return x(q)},J=function(p,q,t,v){return p.catch(function(y){Object(e.b)(y);return v(q,t)})},G=function(p,q,t){var v;if(t.isAsync){var y=q[0](p,t);for(v=1;v<q.length;++v)y=J(y,p,t,q[v]);return y}for(v=0;v<q.length;++v)try{return q[v](p,
t)}catch(B){Object(e.b)(B.message)}throw Error("");},I=function(p,q,t,v){return G(p,[D,E,F],{compressedMaximum:q,isAsync:t,shouldOutputArray:v})},H=function(p,q,t,v){return G(p,[E,D,F],{compressedMaximum:q,isAsync:t,shouldOutputArray:v})}},function(g,b,d){d.d(b,"b",function(){return c});d.d(b,"a",function(){return e});var c=function(k){if("string"===typeof k){for(var a=new Uint8Array(k.length),f=k.length,h=0;h<f;h++)a[h]=k.charCodeAt(h);return a}return k},e=function(k){if("string"!==typeof k){for(var a=
"",f=0,h=k.length,l;f<h;)l=k.subarray(f,f+1024),f+=1024,a+=String.fromCharCode.apply(null,l);return a}return k}},function(g,b,d){function c(k,a,f){return new Promise(function(h){if(!k)return h();var l=f.document.createElement("script");l.type="text/javascript";l.onload=function(){h()};l.onerror=function(){a&&Object(e.b)(a);h()};l.src=k;f.document.getElementsByTagName("head")[0].appendChild(l)})}d.d(b,"a",function(){return c});var e=d(0)},function(g,b,d){function c(f,h,l){function r(w){n=n||Date.now();
return w?(Object(e.a)("load","Try instantiateStreaming"),fetch(Object(k.a)(f)).then(function(m){return WebAssembly.instantiateStreaming(m,h)}).catch(function(m){Object(e.a)("load","instantiateStreaming Failed "+f+" message "+m.message);return r(!1)})):Object(k.b)(f,l,!0,!0).then(function(m){u=Date.now();Object(e.a)("load","Request took "+(u-n)+" ms");return WebAssembly.instantiate(m,h)})}var u,n;return r(!!WebAssembly.instantiateStreaming).then(function(w){Object(e.a)("load","WASM compilation took "+
(Date.now()-(u||n))+" ms");return w})}d.d(b,"a",function(){return c});var e=d(0),k=d(2),a=d(4);d.d(b,"b",function(){return a.a})},function(g,b,d){function c(k,a,f,h){function l(r){return r instanceof f?r:new f(function(u){u(r)})}return new (f||(f=Promise))(function(r,u){function n(x){try{m(h.next(x))}catch(A){u(A)}}function w(x){try{m(h["throw"](x))}catch(A){u(A)}}function m(x){x.done?r(x.value):l(x.value).then(n,w)}m((h=h.apply(k,a||[])).next())})}function e(k,a){function f(m){return function(x){return h([m,
x])}}function h(m){if(r)throw new TypeError("Generator is already executing.");for(;l;)try{if(r=1,u&&(n=m[0]&2?u["return"]:m[0]?u["throw"]||((n=u["return"])&&n.call(u),0):u.next)&&!(n=n.call(u,m[1])).done)return n;if(u=0,n)m=[m[0]&2,n.value];switch(m[0]){case 0:case 1:n=m;break;case 4:return l.label++,{value:m[1],done:!1};case 5:l.label++;u=m[1];m=[0];continue;case 7:m=l.ops.pop();l.trys.pop();continue;default:if(!(n=l.trys,n=0<n.length&&n[n.length-1])&&(6===m[0]||2===m[0])){l=0;continue}if(3===m[0]&&
(!n||m[1]>n[0]&&m[1]<n[3]))l.label=m[1];else if(6===m[0]&&l.label<n[1])l.label=n[1],n=m;else if(n&&l.label<n[2])l.label=n[2],l.ops.push(m);else{n[2]&&l.ops.pop();l.trys.pop();continue}}m=a.call(k,l)}catch(x){m=[6,x],u=0}finally{r=n=0}if(m[0]&5)throw m[1];return{value:m[0]?m[1]:void 0,done:!0}}var l={label:0,sent:function(){if(n[0]&1)throw n[1];return n[1]},trys:[],ops:[]},r,u,n,w;return w={next:f(0),"throw":f(1),"return":f(2)},"function"===typeof Symbol&&(w[Symbol.iterator]=function(){return this}),
w}d.d(b,"a",function(){return c});d.d(b,"b",function(){return e})},function(g,b,d){d.d(b,"a",function(){return f});var c=d(2),e=d(5),k=d(8),a=function(){function h(l){var r=this;this.promise=l.then(function(u){r.response=u;r.status=200})}h.prototype.addEventListener=function(l,r){this.promise.then(r)};return h}(),f=function(h,l,r){if(Object(k.a)()&&!r){self.Module.instantiateWasm=function(n,w){return Object(e.a)(h+"Wasm.wasm",n,l["Wasm.wasm"]).then(function(m){w(m.instance)})};if(l.disableObjectURLBlobs){importScripts(h+
"Wasm.js");return}r=Object(c.b)(h+"Wasm.js.mem",l["Wasm.js.mem"],!1,!1)}else{if(l.disableObjectURLBlobs){importScripts((self.Module.asmjsPrefix?self.Module.asmjsPrefix:"")+h+".js");return}r=Object(c.b)((self.Module.asmjsPrefix?self.Module.asmjsPrefix:"")+h+".js.mem",l[".js.mem"],!1);var u=Object(c.c)((self.Module.memoryInitializerPrefixURL?self.Module.memoryInitializerPrefixURL:"")+h+".mem",l[".mem"],!0,!0);self.Module.memoryInitializerRequest=new a(u)}r=new Blob([r],{type:"application/javascript"});
importScripts(URL.createObjectURL(r))}},function(g,b,d){d.d(b,"a",function(){return w});var c="undefined"===typeof window?self:window;g=function(){var m=navigator.userAgent.toLowerCase();return(m=/(msie) ([\w.]+)/.exec(m)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(m))?parseInt(m[2],10):m}();var e=function(){var m=c.navigator.userAgent.match(/OPR/),x=c.navigator.userAgent.match(/Maxthon/),A=c.navigator.userAgent.match(/Edge/);return c.navigator.userAgent.match(/Chrome\/(.*?) /)&&!m&&!x&&!A}();(function(){if(!e)return null;
var m=c.navigator.userAgent.match(/Chrome\/([0-9]+)\./);return m?parseInt(m[1],10):m})();var k=!!navigator.userAgent.match(/Edge/i)||navigator.userAgent.match(/Edg\/(.*?)/)&&c.navigator.userAgent.match(/Chrome\/(.*?) /);(function(){if(!k)return null;var m=c.navigator.userAgent.match(/Edg\/([0-9]+)\./);return m?parseInt(m[1],10):m})();b=/iPad|iPhone|iPod/.test(c.navigator.platform)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints||/iPad|iPhone|iPod/.test(c.navigator.userAgent);var a=function(){var m=
c.navigator.userAgent.match(/.*\/([0-9\.]+)\s(Safari|Mobile).*/i);return m?parseFloat(m[1]):m}(),f=/^((?!chrome|android).)*safari/i.test(c.navigator.userAgent)||/^((?!chrome|android).)*$/.test(c.navigator.userAgent)&&b,h=c.navigator.userAgent.match(/Firefox/);(function(){if(!h)return null;var m=c.navigator.userAgent.match(/Firefox\/([0-9]+)\./);return m?parseInt(m[1],10):m})();g||/Android|webOS|Touch|IEMobile|Silk/i.test(navigator.userAgent);navigator.userAgent.match(/(iPad|iPhone|iPod)/i);c.navigator.userAgent.indexOf("Android");
var l=/Mac OS X 10_13_6.*\(KHTML, like Gecko\)$/.test(c.navigator.userAgent),r=c.navigator.userAgent.match(/(iPad|iPhone).+\sOS\s((\d+)(_\d)*)/i)?14<=parseInt(c.navigator.userAgent.match(/(iPad|iPhone).+\sOS\s((\d+)(_\d)*)/i)[3],10):!1,u=!(!self.WebAssembly||!self.WebAssembly.validate),n=-1<c.navigator.userAgent.indexOf("Edge/16")||-1<c.navigator.userAgent.indexOf("MSAppHost"),w=function(){return u&&!n&&!(!r&&(f&&14>a||l))}},function(g,b,d){g.exports=d(10)},function(g,b,d){function c(k,a){if(null==
a||a>k.length)a=k.length;for(var f=0,h=Array(a);f<a;f++)h[f]=k[f];return h}d.r(b);g=d(7);var e={};location.search.slice(1).split("&").forEach(function(k){k=k.split("=");var a;var f=Array.isArray(k)?k:void 0;if(!f)a:{var h=null==k?null:"undefined"!=typeof Symbol&&k[Symbol.iterator]||k["@@iterator"];if(null!=h){var l,r,u=[],n=!0,w=!1;try{for(l=(h=h.call(k)).next;!(n=(a=l.call(h)).done)&&(u.push(a.value),2!==u.length);n=!0);}catch(x){w=!0;var m=x}finally{try{if(!n&&null!=h["return"]&&(r=h["return"](),
Object(r)!==r)){f=void 0;break a}}finally{if(w)throw m;}}f=u}else f=void 0}if(!(a=f))a:{if(k){if("string"===typeof k){a=c(k,2);break a}a=Object.prototype.toString.call(k).slice(8,-1);"Object"===a&&k.constructor&&(a=k.constructor.name);if("Map"===a||"Set"===a){a=Array.from(k);break a}if("Arguments"===a||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(a)){a=c(k,2);break a}}a=void 0}if(!(k=a))throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
e[k[0]]=k[1]});self.Module={};self.basePath=e.externalPath;self.workerCallbackId=null;self.runtimeInitialized=!1;(function(){function k(){if(f&&self.runtimeInitialized){var r=f;f=null;r.forEach(function(u){onmessage(u)})}}function a(){k();f&&setTimeout(a,100)}var f=null,h=null,l=0;onmessage=function(r){if(self.runtimeInitialized){k();var u=Module["_".concat(r.data.action)];if(!u)throw Error("invalid worker function to call: ".concat(r.data.funcName));var n=r.data.data;if(n){n.byteLength||(n=new Uint8Array(n));
if(!h||l<n.length)h&&Module._free(h),l=n.length,h=Module._malloc(n.length);Module.HEAP8.set(n,h)}self.workerCallbackId=r.data.callbackId;try{n?u(h,n.length):u(0,0)}catch(w){postMessage({callbackId:self.workerCallbackId,data:{error:w.toString()}})}}else f||(f=[],setTimeout(a,100)),f.push(r)}})();Object(g.a)("OfficeEditorWorker",{"Wasm.wasm":1E8,"Wasm.js.mem":1E5,".js.mem":5E6,".mem":3E6},!!navigator.userAgent.match(/Edge/i))}]);}).call(this || window)
