/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{585:function(xa,ta,h){h.r(ta);var ra=h(0),na=h(607),oa=h(608),ja;(function(ka){ka[ka.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ka[ka.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ka[ka.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ja||(ja={}));xa=function(){function ka(fa){this.ba=fa;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED}ka.prototype.Gwa=function(){var fa=this;return function(x,
y,r){return Object(ra.b)(fa,void 0,void 0,function(){var n,f,a,b,e,w,ba,ca=this,ia;return Object(ra.d)(this,function(z){switch(z.label){case 0:if(this.state!==ja.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];n=this.ba.getDocument().Fx();return[4,this.rua(n)];case 1:f=z.aa(),a=this.moa(f),this.AR=null!==(ia=null===a||void 0===a?void 0:a.parse())&&void 0!==ia?ia:null,this.state=null===this.AR?ja.EXTERNAL_XFDF_NOT_AVAILABLE:ja.EXTERNAL_XFDF_AVAILABLE,z.label=2;case 2:if(this.state===ja.EXTERNAL_XFDF_NOT_AVAILABLE)return r(x),
[2];b=new DOMParser;e=b.parseFromString(x,"text/xml");y.forEach(function(ea){ca.merge(e,ca.AR,ea-1)});w=new XMLSerializer;ba=w.serializeToString(e);r(ba);return[2]}})})}};ka.prototype.iX=function(fa){this.rua=fa};ka.prototype.Vf=function(){this.AR=void 0;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED};ka.prototype.moa=function(fa){return fa?Array.isArray(fa)?new na.a(fa):"string"!==typeof fa?null:(new DOMParser).parseFromString(fa,"text/xml").querySelector("xfdf > add")?new na.a(fa):new oa.a(fa):null};
ka.prototype.merge=function(fa,x,y){var r=this;0===y&&(this.bAa(fa,x.Dt),this.dAa(fa,x.hR));var n=x.ea[y];n&&(this.eAa(fa,n.dr),this.gAa(fa,n.yea,x.hC),this.fAa(fa,n.page,y),this.cAa(fa,n.e4));n=this.ba.Eb();if(y===n-1){var f=x.hC;Object.keys(f).forEach(function(a){f[a].oT||r.q9(fa,a,f[a])})}};ka.prototype.bAa=function(fa,x){null!==x&&(fa=this.iB(fa),this.cv(fa,"calculation-order",x))};ka.prototype.dAa=function(fa,x){null!==x&&(fa=this.iB(fa),this.cv(fa,"document-actions",x))};ka.prototype.eAa=function(fa,
x){var y=this,r=this.hB(fa.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(n){y.cv(r,'[name="'+n+'"]',x[n])})};ka.prototype.gAa=function(fa,x,y){var r=this;if(0!==x.length){var n=this.iB(fa);x.forEach(function(f){var a=f.getAttribute("field"),b=y[a];b&&(r.q9(fa,a,b),r.cv(n,"null",f))})}};ka.prototype.q9=function(fa,x,y){var r=this.iB(fa),n=r.querySelector('ffield[name="'+x+'"]');null!==y.oJ&&null===n&&this.cv(r,'ffield[name="'+x+'"]',y.oJ);fa=this.hB(fa.querySelector("xfdf"),"xfdf > fields",
"fields");x=x.split(".");this.bW(fa,x,0,y.value);y.oT=!0};ka.prototype.fAa=function(fa,x,y){null!==x&&(fa=this.iB(fa),fa=this.hB(fa,"pages"),this.cv(fa,'[number="'+(y+1)+'"]',x))};ka.prototype.cAa=function(fa,x){Object.keys(x).forEach(function(y){(y=fa.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};ka.prototype.bW=function(fa,x,y,r){if(y===x.length)x=document.createElementNS("","value"),x.textContent=r,this.cv(fa,"value",x);else{var n=x[y];this.hB(fa,'[name="'+n+'"]',"field").setAttribute("name",
n);fa=fa.querySelectorAll('[name="'+n+'"]');1===fa.length?this.bW(fa[0],x,y+1,r):(n=this.Dsa(fa),this.bW(y===x.length-1?n:this.fJa(fa,n),x,y+1,r))}};ka.prototype.Dsa=function(fa){for(var x=null,y=0;y<fa.length;y++){var r=fa[y];if(0===r.childElementCount||1===r.childElementCount&&"value"===r.children[0].tagName){x=r;break}}return x};ka.prototype.fJa=function(fa,x){for(var y=0;y<fa.length;y++)if(fa[y]!==x)return fa[y];return null};ka.prototype.cv=function(fa,x,y){x=fa.querySelector(x);null!==x&&fa.removeChild(x);
fa.appendChild(y)};ka.prototype.iB=function(fa){var x=fa.querySelector("pdf-info");if(null!==x)return x;x=this.hB(fa.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};ka.prototype.hB=function(fa,x,y){var r=fa.querySelector(x);if(null!==r)return r;r=document.createElementNS("",y||x);fa.appendChild(r);return r};return ka}();ta["default"]=xa},596:function(xa,ta){xa=function(){function h(){}
h.prototype.DH=function(ra){var na={Dt:null,hR:null,hC:{},ea:{}};ra=(new DOMParser).parseFromString(ra,"text/xml");na.Dt=ra.querySelector("pdf-info calculation-order");na.hR=ra.querySelector("pdf-info document-actions");na.hC=this.FBa(ra);na.ea=this.TBa(ra);return na};h.prototype.FBa=function(ra){var na=ra.querySelector("fields");ra=ra.querySelectorAll("pdf-info > ffield");if(null===na&&null===ra)return{};var oa={};this.yka(oa,na);this.wka(oa,ra);return oa};h.prototype.yka=function(ra,na){if(null!==
na&&na.children){for(var oa=[],ja=0;ja<na.children.length;ja++){var ka=na.children[ja];oa.push({name:ka.getAttribute("name"),element:ka})}for(;0!==oa.length;)for(na=oa.shift(),ja=0;ja<na.element.children.length;ja++)ka=na.element.children[ja],"value"===ka.tagName?ra[na.name]={value:ka.textContent,oJ:null,oT:!1}:ka.children&&oa.push({name:na.name+"."+ka.getAttribute("name"),element:ka})}};h.prototype.wka=function(ra,na){na.forEach(function(oa){var ja=oa.getAttribute("name");ra[ja]?ra[ja].oJ=oa:ra[ja]=
{value:null,oJ:oa,oT:!1}})};h.prototype.TBa=function(ra){var na=this,oa={};ra.querySelectorAll("pdf-info widget").forEach(function(ja){var ka=parseInt(ja.getAttribute("page"),10)-1;na.DK(oa,ka);oa[ka].yea.push(ja)});ra.querySelectorAll("pdf-info page").forEach(function(ja){var ka=parseInt(ja.getAttribute("number"),10)-1;na.DK(oa,ka);oa[ka].page=ja});this.i6(ra).forEach(function(ja){var ka=parseInt(ja.getAttribute("page"),10),fa=ja.getAttribute("name");na.DK(oa,ka);oa[ka].dr[fa]=ja});this.R5(ra).forEach(function(ja){var ka=
parseInt(ja.getAttribute("page"),10);ja=ja.textContent;na.DK(oa,ka);oa[ka].e4[ja]=!0});return oa};h.prototype.DK=function(ra,na){ra[na]||(ra[na]={dr:{},e4:{},yea:[],page:null})};return h}();ta.a=xa},607:function(xa,ta,h){var ra=h(0),na=h(1);h.n(na);xa=function(oa){function ja(ka){var fa=oa.call(this)||this;fa.msa=Array.isArray(ka)?ka:[ka];return fa}Object(ra.c)(ja,oa);ja.prototype.parse=function(){var ka=this,fa={Dt:null,hR:null,hC:{},ea:{}};this.msa.forEach(function(x){fa=Object(na.merge)(fa,ka.DH(x))});
return fa};ja.prototype.i6=function(ka){var fa=[];ka.querySelectorAll("add > *").forEach(function(x){fa.push(x)});ka.querySelectorAll("modify > *").forEach(function(x){fa.push(x)});return fa};ja.prototype.R5=function(ka){return ka.querySelectorAll("delete > *")};return ja}(h(596).a);ta.a=xa},608:function(xa,ta,h){var ra=h(0);xa=function(na){function oa(ja){var ka=na.call(this)||this;ka.nsa=ja;return ka}Object(ra.c)(oa,na);oa.prototype.parse=function(){return this.DH(this.nsa)};oa.prototype.i6=function(ja){return ja.querySelectorAll("annots > *")};
oa.prototype.R5=function(){return[]};return oa}(h(596).a);ta.a=xa}}]);}).call(this || window)
