/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{569:function(xa,ta,h){h.r(ta);h.d(ta,"ByteRangeRequest",function(){return w});var ra=h(0),na=h(1);h.n(na);var oa=h(3),ja=h(195);xa=h(121);var ka=h(324),fa=h(93),x=h(97),y=h(323),r=h(216);h=h(492);var n=[],f=[],a=window,b=function(){return function(){this.gq=1}}(),e;(function(ca){ca[ca.UNSENT=0]="UNSENT";ca[ca.DONE=4]="DONE"})(e||(e={}));var w=function(){function ca(ia,z,ea,aa){var ma=this;this.url=ia;this.range=z;this.Jf=ea;
this.withCredentials=aa;this.Vha=e;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");aa&&(this.request.withCredentials=aa);ba.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(z.stop)?this.request.setRequestHeader("Range","bytes="+z.start):this.request.setRequestHeader("Range",["bytes=",z.start,"-",z.stop-1].join("")));ea&&Object.keys(ea).forEach(function(la){ma.request.setRequestHeader(la,ea[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ca.prototype.start=function(ia){var z=this,ea=this.request;ea.onreadystatechange=function(){if(z.aborted)return z.status=y.a.ABORTED,ia({code:y.a.ABORTED});if(this.readyState===z.Vha.DONE){z.ZJ();var aa=0===window.document.URL.indexOf("file:///");200===ea.status||206===ea.status||aa&&0===ea.status?(aa=a.F6(this),z.cY(aa,ia)):(z.status=y.a.ERROR,
ia({code:z.status,status:z.status}))}};this.request.send(null);this.status=y.a.STARTED};ca.prototype.cY=function(ia,z){this.status=y.a.SUCCESS;if(z)return z(!1,ia)};ca.prototype.abort=function(){this.ZJ();this.aborted=!0;this.request.abort()};ca.prototype.ZJ=function(){var ia=Object(r.c)(this.url,this.range,f);-1!==ia&&f.splice(ia,1);if(0<n.length){ia=n.shift();var z=new ca(ia.url,ia.range,this.Jf,this.withCredentials);ia.request=z;f.push(ia);z.start(Object(r.d)(ia))}};ca.prototype.extend=function(ia){var z=
Object.assign({},this,ia.prototype);z.constructor=ia;return z};return ca}(),ba=function(ca){function ia(z,ea,aa,ma,la){aa=ca.call(this,z,aa,ma)||this;aa.Zl={};aa.gI=ea;aa.url=z;aa.DISABLE_RANGE_HEADER=!1;aa.tE=w;aa.tZ=3;aa.Jf=la||{};return aa}Object(ra.c)(ia,ca);ia.prototype.KB=function(z,ea,aa){var ma=-1===z.indexOf("?")?"?":"&";switch(aa){case !1:case x.a.NEVER_CACHE:z=z+ma+"_="+Object(na.uniqueId)();break;case !0:case x.a.CACHE:z=z+ma+"_="+ea.start+","+(Object(na.isUndefined)(ea.stop)?"":ea.stop)}return z};
ia.prototype.J3=function(z,ea,aa,ma){void 0===aa&&(aa={});return new this.tE(z,ea,aa,ma)};ia.prototype.bsa=function(z,ea,aa,ma,la){for(var ha=0;ha<n.length;ha++)if(Object(na.isEqual)(n[ha].range,ea)&&Object(na.isEqual)(n[ha].url,z))return n[ha].$i.push(ma),n[ha].mL++,null;for(ha=0;ha<f.length;ha++)if(Object(na.isEqual)(f[ha].range,ea)&&Object(na.isEqual)(f[ha].url,z))return f[ha].$i.push(ma),f[ha].mL++,null;aa={url:z,range:ea,gI:aa,$i:[ma],mL:1};if(0===n.length&&f.length<this.tZ)return f.push(aa),
aa.request=this.J3(z,ea,la,this.withCredentials),aa;n.push(aa);return null};ia.prototype.es=function(z,ea,aa){var ma=this.KB(z,ea,this.gI);(z=this.bsa(ma,ea,this.gI,aa,this.Jf))&&z.request.start(Object(r.d)(z));return function(){var la=Object(r.c)(ma,ea,f);if(-1!==la){var ha=--f[la].mL;0===ha&&f[la].request&&f[la].request.abort()}else la=Object(r.c)(ma,ea,n),-1!==la&&(ha=--n[la].mL,0===ha&&n.splice(la,1))}};ia.prototype.V5=function(){return{start:-ja.a}};ia.prototype.Qwa=function(){var z=-(ja.a+ja.e);
return{start:z-ja.d,end:z}};ia.prototype.By=function(z){var ea=this;this.nI=!0;var aa=ja.a;this.es(this.url,this.V5(),function(ma,la,ha){function qa(){var pa=ea.Le.S5();ea.es(ea.url,pa,function(sa,ua){if(sa)return Object(oa.j)("Error loading central directory: "+sa),z(sa);ua=Object(fa.a)(ua);if(ua.length!==pa.stop-pa.start)return z("Invalid XOD file: Zip central directory data is wrong size! Should be "+(pa.stop-pa.start)+" but is "+ua.length);ea.Le.uaa(ua);ea.pQ=!0;ea.nI=!1;return z(!1)})}if(ma)return Object(oa.j)("Error loading end header: "+
ma),z(ma,la,ha);la=Object(fa.a)(la);if(la.length!==aa)return z("Invalid XOD file: Zip end header data is wrong size!");try{ea.Le=new ka.a(la)}catch(pa){return z(pa)}ea.Le.mza?ea.es(ea.url,ea.Qwa(),function(pa,sa){if(pa)return Object(oa.j)("Error loading zip64 header: "+pa),z(pa);sa=Object(fa.a)(sa);ea.Le.Nza(sa);qa()}):qa()})};ia.prototype.y6=function(z){z(Object.keys(this.Le.Fr))};ia.prototype.eW=function(z,ea){var aa=this;if(this.Le.s3(z)){var ma=this.Le.zC(z);if(ma in this.Zl){var la=this.wj[z];
la.Nw=this.Zl[ma];la.Nw.gq++;la.cancel=la.Nw.cancel}else{var ha=this.Le.yua(z),qa=this.es(this.url,ha,function(sa,ua){sa?(Object(oa.j)('Error loading part "'+z+'": '+sa),aa.es(aa.url,ha,function(wa,Ba){if(wa)return ea(wa,z);aa.yaa(Ba,ha,ma,z,ea)})):aa.yaa(ua,ha,ma,z,ea)}),pa=this.wj[z];pa&&(pa.qda=!0,pa.cancel=function(){pa.Nw.gq--;0===pa.Nw.gq&&(qa(),delete aa.Zl[ma])},this.Zl[ma]=new b(ma),pa.Nw=this.Zl[ma],pa.Nw.cancel=pa.cancel)}}else delete this.wj[z],ea(Error('File not found: "'+z+'"'),z)};
ia.prototype.yaa=function(z,ea,aa,ma,la){if(z.length!==ea.stop-ea.start)la(Error("Part data is wrong size!"),ma);else{do{if(!this.Zl[aa])return;ma=this.Zl[aa].gq;for(var ha=ea.dv.length,qa=0;qa<ha;++qa){var pa=ea.dv[qa];la(!1,pa.av,z["string"===typeof z?"substring":"subarray"](pa.start,pa.stop),this.Le.Y7(pa.av));pa.av in this.wj&&delete this.wj[pa.av]}}while(ma!==this.Zl[aa].gq);delete this.Zl[aa]}};ia.DISABLE_RANGE_HEADER=!1;ia.tZ=3;return ia}(xa.a);(function(ca){function ia(z,ea,aa){var ma=ca.call(this)||
this,la;for(la in z)ma[la]=z[la];ma.xOa=z;ma.startOffset=ea;ma.endOffset=aa;ma.J3=function(ha,qa,pa,sa){Object(na.isUndefined)(qa.stop)?(qa.start+=ma.endOffset,qa.stop=ma.endOffset):(qa.start+=ma.startOffset,qa.stop+=ma.startOffset);ha=ma.KB(ma.url,qa,ma.gI);return new z.tE(ha,qa,pa,sa)};return ma}Object(ra.c)(ia,ca);return ia})(ba);Object(h.a)(ba);Object(h.b)(ba);ta["default"]=ba}}]);}).call(this || window)
