/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{578:function(xa,ta,h){h.r(ta);var ra=h(0),na=h(1);h.n(na);var oa=h(3),ja=h(195);xa=h(57);var ka=h(121),fa=h(324),x=h(97),y=h(323);h=h(492);var r=window,n=function(){function b(e,w,ba){var ca=-1===e.indexOf("?")?"?":"&";switch(w){case x.a.NEVER_CACHE:this.url=e+ca+"_="+Object(na.uniqueId)();break;default:this.url=e}this.Jf=ba;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}b.prototype.start=function(e,w){var ba=this,ca=this,ia=this.request,z;ca.AD=0;e&&Object.keys(e).forEach(function(ea){ba.request.setRequestHeader(ea,e[ea])});w&&(this.request.withCredentials=w);this.SL=setInterval(function(){var ea=0===window.document.URL.indexOf("file:///");ea=200===ia.status||
ea&&0===ia.status;if(ia.readyState!==y.b.DONE||ea){try{ia.responseText}catch(aa){return}ca.AD<ia.responseText.length&&(z=ca.WCa())&&ca.trigger(b.Events.DATA,[z]);0===ia.readyState&&(clearInterval(ca.SL),ca.trigger(b.Events.DONE))}else clearInterval(ca.SL),ca.trigger(b.Events.DONE,["Error received return status "+ia.status])},1E3);this.request.send(null);this.status=y.a.STARTED};b.prototype.WCa=function(){var e=this.request,w=e.responseText;if(0!==w.length)if(this.AD===w.length)clearInterval(this.SL),
this.trigger(b.Events.DONE);else return w=Math.min(this.AD+3E6,w.length),e=r.F6(e,this.AD,!0,w),this.AD=w,e};b.prototype.abort=function(){clearInterval(this.SL);var e=this;this.request.onreadystatechange=function(){Object(oa.j)("StreamingRequest aborted");e.status=y.a.ABORTED;return e.trigger(b.Events.ABORTED)};this.request.abort()};b.prototype.finish=function(){var e=this;this.request.onreadystatechange=function(){e.status=y.a.SUCCESS;return e.trigger(b.Events.DONE)};this.request.abort()};b.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return b}();Object(xa.a)(n);var f;(function(b){b[b.LOCAL_HEADER=0]="LOCAL_HEADER";b[b.FILE=1]="FILE";b[b.CENTRAL_DIR=2]="CENTRAL_DIR"})(f||(f={}));var a=function(b){function e(){var w=b.call(this)||this;w.buffer="";w.state=f.LOCAL_HEADER;w.UX=4;w.Op=null;w.Hy=ja.c;w.Fr={};return w}Object(ra.c)(e,b);e.prototype.OCa=function(w){var ba;for(w=this.buffer+w;w.length>=this.Hy;)switch(this.state){case f.LOCAL_HEADER:this.Op=ba=this.$Ca(w.slice(0,this.Hy));if(ba.wz!==
ja.g)throw Error("Wrong signature in local header: "+ba.wz);w=w.slice(this.Hy);this.state=f.FILE;this.Hy=ba.dQ+ba.Ru+ba.fC+this.UX;this.trigger(e.Events.HEADER,[ba]);break;case f.FILE:this.Op.name=w.slice(0,this.Op.Ru);this.Fr[this.Op.name]=this.Op;ba=this.Hy-this.UX;var ca=w.slice(this.Op.Ru+this.Op.fC,ba);this.trigger(e.Events.FILE,[this.Op.name,ca,this.Op.xQ]);w=w.slice(ba);if(w.slice(0,this.UX)===ja.h)this.state=f.LOCAL_HEADER,this.Hy=ja.c;else return this.state=f.CENTRAL_DIR,!0}this.buffer=w;
return!1};e.Events={HEADER:"header",FILE:"file"};return e}(fa.a);Object(xa.a)(a);xa=function(b){function e(w,ba,ca,ia,z){ca=b.call(this,w,ca,ia)||this;ca.url=w;ca.stream=new n(w,ba);ca.Le=new a;ca.$$=window.createPromiseCapability();ca.Eaa={};ca.Jf=z;return ca}Object(ra.c)(e,b);e.prototype.EE=function(w){var ba=this;this.request([this.nm,this.qo,this.lm]);this.stream.addEventListener(n.Events.DATA,function(ca){try{if(ba.Le.OCa(ca))return ba.stream.finish()}catch(ia){throw ba.stream.abort(),ba.fu(ia),
w(ia),ia;}});this.stream.addEventListener(n.Events.DONE,function(ca){ba.kCa=!0;ba.$$.resolve();ca&&(ba.fu(ca),w(ca))});this.Le.addEventListener(a.Events.HEADER,Object(na.bind)(this.Daa,this));this.Le.addEventListener(a.Events.FILE,Object(na.bind)(this.qDa,this));return this.stream.start(this.Jf,this.withCredentials)};e.prototype.y6=function(w){var ba=this;this.$$.promise.then(function(){w(Object.keys(ba.Le.Fr))})};e.prototype.us=function(){return!0};e.prototype.request=function(w){var ba=this;this.kCa&&
w.forEach(function(ca){ba.Eaa[ca]||ba.wJa(ca)})};e.prototype.Daa=function(){};e.prototype.abort=function(){this.stream&&this.stream.abort()};e.prototype.wJa=function(w){this.trigger(ka.a.Events.PART_READY,[{Lb:w,error:"Requested part not found",nl:!1,ji:!1}])};e.prototype.qDa=function(w,ba,ca){this.Eaa[w]=!0;this.trigger(ka.a.Events.PART_READY,[{Lb:w,data:ba,nl:!1,ji:!1,error:null,se:ca}])};return e}(ka.a);Object(h.a)(xa);Object(h.b)(xa);ta["default"]=xa}}]);}).call(this || window)
