/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{580:function(xa,ta,h){function ra(){return!1}function na(ba,ca,ia){if(!(ca in w))return!0;ca=w[ca];for(var z=0;z<ca.length;z++){var ea=ba;var aa=ca[z];var ma=ia;if(aa.name in ea){var la="",ha=!1;ea=ea[aa.name];switch(aa.type){case "s":la="String";ha=Object(ka.isString)(ea);break;case "a":la="Array";ha=Object(ka.isArray)(ea);break;case "n":la="Number";ha=Object(ka.isNumber)(ea)&&Object(ka.isFinite)(ea);break;case "o":la="Object",
ha=Object(ka.isObject)(ea)&&!Object(ka.isArray)(ea)}ha||ma.reject('Expected response field "'+aa.name+'" to have type '+la);aa=ha}else ma.reject('Response missing field "'+aa.name+'"'),aa=!1;if(!aa)return!1}return!0}function oa(ba){for(var ca=0,ia=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];ca<ia.length;ca++){var z=ia[ca],ea=z;z=z.charAt(0).toUpperCase()+z.slice(1);ba[ea]&&(Object.defineProperty(ba,z,Object.getOwnPropertyDescriptor(ba,
ea)),delete ba[ea])}return ba}h.r(ta);var ja=h(0),ka=h(1);h.n(ka);var fa=h(3);xa=h(57);var x=h(34),y=h(598),r=h(121),n=h(492),f=h(53),a=h(216),b=function(){function ba(){this.request=this.result=null;this.state=0;var ca=this;ca.promise=new Promise(function(ia,z){ca.resolve=function(){if(0===ca.state||4===ca.state)ca.state=1,ca.result=arguments[0],ia.apply(null,arguments)};ca.reject=function(){if(0===ca.state||4===ca.state)ca.state=2,z.apply(null,arguments)}})}ba.prototype.ty=function(){return 1===
(this.state&1)};ba.prototype.Wya=function(){return 2===(this.state&2)};ba.prototype.Jl=function(){return!this.Wya()&&!this.ty()};ba.prototype.mya=function(){return 4===(this.state&4)};ba.prototype.jX=function(){this.state|=4};return ba}(),e=function(){function ba(){this.$x={};this.Hc=[]}ba.prototype.pop=function(){var ca=this.Hc.pop();this.$x[ca.key]=void 0;return ca};ba.prototype.push=function(ca,ia){ia={key:ca,data:ia};this.Hc.push(ia);this.$x[ca]=ia.data};ba.prototype.contains=function(ca){return!!this.$x[ca]};
ba.prototype.get=function(ca){return this.$x[ca]};ba.prototype.set=function(ca,ia){var z=this;this.$x[ca]=ia;this.Hc.forEach(function(ea,aa){ea.key===ca&&(z.Hc[aa]=ea)})};ba.prototype.remove=function(ca){var ia=this;this.$x[ca]=void 0;this.Hc.forEach(function(z,ea){z.key===ca&&ia.Hc.splice(ea,1)})};ba.prototype.length=function(){return this.Hc.length};return ba}(),w={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",
type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};h=function(){function ba(ca,ia,z){var ea=this;this.VX=this.n4=!1;this.vj=this.rN=this.$z=this.eg=this.vB=this.ls=this.uB=this.zq=
null;this.Xp=new b;this.Mt=new b;this.xI=!1;this.Ah=this.lg=this.mg=this.oh=null;this.Xh=[];this.uJ=[];this.cache={};this.timeStamp=0;this.pj=[];this.Tl=[];this.ER=null;this.Z3=!1;this.Wba=this.id=null;this.FU=this.A7=ra;this.Qh=0;this.jT=!1;this.L9=1;this.Pl={};this.vw=0;this.ez=new e;ia.endsWith("/")||(ia+="/");z=z||{};this.n4=z.disableWebsockets||!1;this.VX=z.singleServerMode||!1;null!=z.customQueryParameters&&Object(f.b)("wvsQueryParameters",z.customQueryParameters);ia.endsWith("blackbox/")||
(ia+="blackbox/");this.zq=z.uploadData||null;this.$z=z.uriData||null;this.uB=z.cacheKey||null;if(this.ls=z.officeOptions||null)this.ls=oa(this.ls);this.eg=z.rasterizerOptions||null;this.vB=z.cadOptions||null;this.Hg=ia;this.fR=ca;this.zs(!0);this.Uw=(new y.a(ia,null,this.ik())).eta(!this.n4,function(aa){ea.ZAa(aa)},function(){return null},function(){ea.xI=!1},function(){ea.REa()})}ba.prototype.fpa=function(){var ca=this;return new Promise(function(ia,z){var ea=new XMLHttpRequest;ea.open("GET",ca.Hg+
"ck");ea.withCredentials=ca.ik();ea.onreadystatechange=function(){ea.readyState===XMLHttpRequest.DONE&&(200===ea.status?ia():z())};ea.send()})};ba.prototype.MGa=function(ca){this.A7=ca||ra;this.FU=ra};ba.prototype.mna=function(){this.qba();return this.Uw.bu()};ba.prototype.qba=function(){Object(ja.b)(this,void 0,void 0,function(){return Object(ja.d)(this,function(ca){switch(ca.label){case 0:return this.Mt=new b,this.Xp=new b,this.xI=!1,this.id=null,this.Z3=!1,[4,this.fpa().catch(function(){})];case 1:return ca.aa(),
[2]}})})};ba.prototype.REa=function(){this.A7();this.qba();this.oh&&(this.oh.Jl()?this.Bj(this.oh.request):this.oh.ty()&&this.FU(this.oh.result.url,"pdf")&&(this.oh=null,this.nba()));this.Ah&&this.Ah.Jl()&&this.Bj(this.Ah.request);this.mg&&this.mg.Jl()?this.Bj(this.mg.request):this.lg&&this.lg.Jl()&&this.k7();var ca;for(ca=0;ca<this.pj.length;ca++)this.pj[ca]&&(this.pj[ca].Jl()?this.Bj(this.pj[ca].request):this.pj[ca].ty()&&this.FU(this.pj[ca].result.url,"image")&&(this.pj[ca]=null,this.fM(Object(ka.uniqueId)(),
ca)));for(ca=0;ca<this.Tl.length;ca++)this.Tl[ca]&&this.Tl[ca].Jl()&&!this.Tl[ca].mya()&&this.Bj(this.Tl[ca].request);for(ca=0;ca<this.Xh.length;ca++)this.Xh[ca]&&this.Xh[ca].Jl()&&this.Bj(this.Xh[ca].request)};ba.prototype.Gxa=function(){return this.xI?Promise.resolve():(this.xI=!0,this.timeStamp=Date.now(),this.Uw.EK())};ba.prototype.gKa=function(){var ca=this,ia,z,ea,aa,ma;return new Promise(function(la,ha){if(ca.zq)ia=new FormData,ia.append("file",ca.zq.fileHandle,ca.zq.fileHandle.name),ca.ls&&
ia.append("officeOptions",JSON.stringify(ca.ls)),ca.eg&&ia.append("rasterizerOptions",JSON.stringify(ca.eg)),ca.vB&&ia.append("cadOptions",ca.vB.getJsonString()),ca.uB&&ia.append("cacheKey",ca.uB),z=ca.zq.loadCallback,aa="upload",ea=ca.zq.extension;else if(ca.$z)ia={uri:ca.$z.uri,XOa:ca.$z.shareId},ia=Object.keys(ia).map(function(sa){return sa+"="+(ia[sa]?encodeURIComponent(ia[sa]):"")}).join("&"),ma="application/x-www-form-urlencoded; charset=UTF-8",z=ca.$z.loadCallback,aa="url",ea=ca.$z.extension;
else{la();return}var qa=new XMLHttpRequest,pa=Object(x.k)(ca.Hg,"AuxUpload");pa=Object(a.a)(pa,{type:aa,ext:ea});qa.open("POST",pa);qa.withCredentials=ca.ik();ma&&qa.setRequestHeader("Content-Type",ma);qa.addEventListener("load",function(){if(qa.readyState===qa.DONE&&200===qa.status){var sa=JSON.parse(qa.response);ca.fR=sa.uri;z(sa);la(sa)}});qa.addEventListener("error",function(){ha(qa.statusText+" "+JSON.stringify(qa))});ca.zq&&null!=ca.zq.onProgress&&(qa.upload.onprogress=function(sa){ca.zq.onProgress(sa)});
qa.send(ia)})};ba.prototype.GEa=function(ca){this.password=ca||null;this.Xp.ty()||(this.Xp=new b,this.Bj({t:"pages"}));return this.Xp.promise};ba.prototype.EE=function(ca){this.ER=ca||null;this.Xp.ty()||this.Bj({t:"pages"});return this.Xp.promise};ba.prototype.GB=function(ca){ca=Object.assign(ca,{uri:encodeURIComponent(this.fR)});this.ER&&(ca.ext=this.ER);this.vj&&(ca.c=this.vj);this.password&&(ca.pswd=this.password);this.uB&&(ca.cacheKey=this.uB);this.ls&&(ca.officeOptions=this.ls);this.eg&&(ca.rastOptions=
this.eg);this.vB&&(ca.cadOptions=this.vB.mImpl);return ca};ba.prototype.xFa=function(){0<this.ez.length()&&10>=this.vw&&this.yFa(this.ez.pop().data)};ba.prototype.xma=function(ca){0<this.ez.length()&&this.ez.contains(ca)&&this.ez.remove(ca)};ba.prototype.Bj=function(ca){ca=this.GB(ca);this.Uw.send(ca)};ba.prototype.Rba=function(ca,ia){10<this.vw?this.ez.push(ca,ia):(this.vw++,ca=this.GB(ia),this.Uw.send(ca))};ba.prototype.yFa=function(ca){this.vw++;ca=this.GB(ca);this.Uw.send(ca)};ba.prototype.$o=
function(ca){return ca};ba.prototype.z7=function(ca){this.VX&&ca?Object(fa.j)("Server failed health check. Single server mode ignoring check."):!this.mNa&&ca&&3>=this.Qh?(this.jT=!0,this.Uw.bu()):3<this.Qh&&(this.VX=!0)};ba.prototype.ZAa=function(ca){var ia=this,z=ca.data,ea=ca.err,aa=ca.t;switch(aa){case "upload":ea?this.hKa.reject(ea):this.hKa.resolve("Success");break;case "pages":ea?this.Xp.reject(ea):na(z,aa,this.Xp)&&this.Xp.resolve(z);break;case "config":if(ea)this.Mt.reject(ea);else if(na(z,
aa,this.Mt)){this.z7(z.unhealthy);z.id&&(this.id=z.id);if(z.auth){var ma=Object(f.a)("wvsQueryParameters");ma.auth=z.auth;Object(f.b)("wvsQueryParameters",ma)}z.serverVersion&&(this.rN=z.serverVersion,Object(fa.h)("[WebViewer Server] server version: "+this.rN));z.serverID?(this.Qh=z.serverID===this.Wba&&this.jT?this.Qh+1:0,this.Wba=z.serverID):this.Qh=0;this.jT=!1;this.Mt.resolve(z)}break;case "health":ea?this.Mt.reject(ea):na(z,aa,this.Mt)&&this.z7(z.unhealthy);break;case "pdf":z.url=Object(a.a)(this.Hg+
"../"+encodeURI(z.url));ea?this.oh.reject(ea):na(z,aa,this.oh)&&this.oh.resolve(z);break;case "ApString2Xod":z.url=Object(a.a)(this.Hg+"../data/"+encodeURI(z.url));ea?this.Pl[z.rID].reject(ea):na(z,aa,this.Pl[z.rID])&&this.Pl[z.rID].resolve(z);break;case "docmod":z.url=Object(a.a)(this.Hg+"../"+encodeURI(z.url));ea?this.Pl[z.rID].reject(ea):na(z,aa,this.oh)&&this.Pl[z.rID].resolve(z);break;case "xod":if(ea)this.mg&&this.mg.Jl()&&this.mg.reject(ea),this.lg&&this.lg.Jl()&&this.lg.reject(ea);else if(z.notFound)z.noCreate||
this.mg&&this.mg.Jl()&&this.mg.resolve(z),this.lg&&this.lg.Jl()&&this.lg.resolve(z);else{z.url&&(z.url=Object(a.a)(this.Hg+"../"+encodeURI(z.url)));if(!this.lg||this.lg.ty())this.lg=new b,this.lg.request={t:"xod",noCreate:!0};this.mg||(this.mg=new b,this.mg.request={t:"xod"});this.lg.resolve(z);this.mg.resolve(z)}break;case "cAnnots":ma=this.Ah;if(ea)ma.reject(ea);else if(na(z,aa,ma)){ma.jX();var la=[],ha=z.annots;z=function(Ba){var Ca=ha[Ba].s,Aa=ha[Ba].e,La=qa.Hg+"../"+encodeURI(ha[Ba].xfdf),Ea=
"true"===ha[Ba].hasAppearance?Object(a.a)(La+".xodapp"):null,Ka=Object(ka.range)(Ca,Aa+1);la[Ba]={range:Ka,promise:new Promise(function(Na,Oa){var Ra=new XMLHttpRequest;Ra.open("GET",Object(a.a)(La));Ra.responseType="text";Ra.withCredentials=ia.ik();Ra.addEventListener("load",function(){Ra.readyState===Ra.DONE&&200===Ra.status&&Na({Gv:Ra.response,Qo:Ea,range:Ka})});Ra.addEventListener("error",function(){Oa(Ra.statusText+" "+JSON.stringify(Ra))});Ra.send()})}};var qa=this;for(ea=0;ea<ha.length;ea++)z(ea);
ma.resolve(la)}break;case "annots":if(ea)this.Ah.reject(ea);else if(na(z,aa,this.Ah)){this.Ah.jX();var pa=new XMLHttpRequest;ma=this.Hg+"../"+encodeURI(z.url);var sa=z.hasAppearance?Object(a.a)(ma+".xodapp"):null;pa.open("GET",Object(a.a)(ma));pa.responseType="text";pa.withCredentials=this.ik();pa.addEventListener("load",function(){pa.readyState===pa.DONE&&200===pa.status&&ia.Ah.resolve({Gv:pa.response,Qo:sa})});pa.addEventListener("error",function(){ia.Ah.reject(pa.statusText+" "+JSON.stringify(pa))});
pa.send()}break;case "image":this.vw--;var ua=this.pj[z.p];ea?ua.promise.reject(ea):na(z,aa,ua)&&(ua.result=z,ua.result.url=Object(a.a)(this.Hg+"../"+encodeURI(ua.result.url)),ua.resolve(ua.result));break;case "tiles":this.vw--;ua=z.rID;ma=this.Xh[ua];this.Xh[ua]=null;this.uJ.push(ua);if(ea)ma.reject(ea);else if(na(z,aa,ma)){for(ea=0;ea<z.tiles.length;ea++)z.tiles[ea]=Object(a.a)(this.Hg+"../"+encodeURI(z.tiles[ea]));ma.resolve(z)}break;case "text":ua=this.Tl[z.p];if(ea)ua.reject(ea);else if(na(z,
aa,ua)){ua.jX();var wa=new XMLHttpRequest;z=Object(a.a)(this.Hg+"../"+encodeURI(z.url));wa.open("GET",z);wa.withCredentials=this.ik();wa.addEventListener("load",function(){wa.readyState===wa.DONE&&200===wa.status&&(ua.result=JSON.parse(wa.response),ua.resolve(ua.result))});wa.addEventListener("error",function(Ba){ua.reject(wa.statusText+" "+JSON.stringify(Ba))});wa.send()}break;case "progress":"loading"===z.t&&this.trigger(r.a.Events.DOCUMENT_LOADING_PROGRESS,[z.bytes,z.total])}this.xFa();!aa&&ca.echo&&
ca&&"apstring2xod"===ca.echo.t&&(ca=ca.echo.reqID)&&(2<=parseInt(this.rN,10)?this.Pl[ca].reject("Message unhandled by server"):this.Pl[ca].reject())};ba.prototype.Mta=function(){return Object(ja.b)(this,void 0,void 0,function(){return Object(ja.d)(this,function(ca){switch(ca.label){case 0:return[4,this.Gxa()];case 1:return ca.aa(),[2,this.Mt.promise]}})})};ba.prototype.rta=function(ca){for(var ia=this,z=new XMLHttpRequest,ea=Object(a.a)(this.Hg+"aul",{id:this.id}),aa=new FormData,ma={},la=0;la<ca.body.length;la++){var ha=
ca.body[la];ma[ha.id]=ha.NP.w+";"+ha.NP.h;aa.append(ha.id,ha.NP.dataString)}ca={t:"apstring2xod",reqID:this.L9++,parts:ma};var qa=this.GB(ca);aa.append("msg",JSON.stringify(qa));this.Pl[qa.reqID]=new b;z.open("POST",ea);z.withCredentials=this.ik;ea=new Promise(function(pa,sa){z.onreadystatechange=function(){4===z.readyState&&(200===z.status?pa():sa("An error occurred while sending down appearance strings to the server"))}});z.send(aa);return ea.then(function(){return ia.Pl[qa.reqID].promise})};ba.prototype.qna=
function(){var ca=this.rN.split("-")[0].split("."),ia=["1","5","9"];if(3!==ca.length)throw Error("Invalid WVS version length.");if(3!==ia.length)throw Error("Invalid version length.");for(var z=0;z<ca.length;++z){if(ia.length===z||ca[z]>ia[z])return-1;if(ca[z]!==ia[z])return 1}return 0};ba.prototype.Ht=function(){return 0>=this.qna()};ba.prototype.QR=function(){this.Ah||(this.Ah=new b,this.Ht()?this.Ah.request={t:"cAnnots"}:this.Ah.request={t:"annots"},this.Bj(this.Ah.request));return this.Ah.promise};
ba.prototype.fM=function(ca,ia){this.pj[ia]||(this.pj[ia]=new b,this.pj[ia].request={t:"image",p:ia},this.Rba(ca,this.pj[ia].request));return this.pj[ia].promise};ba.prototype.HEa=function(ca){this.Tl[ca]||(this.Tl[ca]=new b,this.Tl[ca].request={t:"text",p:ca},this.Bj(this.Tl[ca].request));return this.Tl[ca].promise};ba.prototype.IEa=function(ca,ia,z,ea,aa){var ma=this.Xh.length;this.uJ.length&&(ma=this.uJ.pop());this.Xh[ma]=new b;this.Xh[ma].request={t:"tiles",p:ia,z:z,r:ea,size:aa,rID:ma};this.Rba(ca,
this.Xh[ma].request);return this.Xh[ma].promise};ba.prototype.nba=function(){this.oh||(this.oh=new b,this.oh.request={t:"pdf"},this.Z3?this.oh.resolve({url:this.fR}):this.Bj(this.oh.request));return this.oh.promise};ba.prototype.k6=function(ca){var ia=this,z=new XMLHttpRequest,ea=Object(a.a)(this.Hg+"aul",{id:this.id}),aa=new FormData,ma={};ca.annots&&(ma.annots="xfdf");ca.watermark&&(ma.watermark="png");ca.redactions&&(ma.redactions="redact");ma={t:"docmod",reqID:this.L9++,parts:ma};ca.print&&(ma.print=
!0);var la=this.GB(ma);aa.append("msg",JSON.stringify(la));return Promise.all([ca.annots,ca.watermark,ca.redactions].map(function(ha){return Promise.resolve(ha)})).then(function(ha){var qa=ha[0],pa=ha[1];ha=ha[2];qa&&aa.append("annots",qa);pa&&aa.append("watermark",pa);ha&&aa.append("redactions",ha);ia.Pl[la.reqID]=new b;z.open("POST",ea);z.withCredentials=ia.ik;qa=new Promise(function(sa,ua){z.onreadystatechange=function(){4===z.readyState&&(200===z.status?sa():ua("An error occurred while sending down annotation data to the server"))}});
z.send(aa);return qa.then(function(){return ia.Pl[la.reqID].promise})})};ba.prototype.k7=function(){this.lg||(this.lg=new b,this.lg.request={t:"xod",noCreate:!0},this.Bj(this.lg.request));return this.lg.promise};ba.prototype.JEa=function(){this.mg||(this.mg=new b,this.mg.request={t:"xod"},this.Bj(this.mg.request));return this.mg.promise};ba.prototype.us=function(){return!0};ba.prototype.request=function(){};ba.prototype.Daa=function(){};ba.prototype.abort=function(){for(var ca=0;ca<this.Xh.length;ca++)this.Xh[ca]&&
(this.Xh[ca].resolve(null),this.Xh[ca]=null,this.uJ.push(ca));this.close()};ba.prototype.wM=function(ca){this.vj=this.vj||{};this.vj.headers=ca};ba.prototype.zs=function(ca){this.vj=this.vj||{};this.vj.internal=this.vj.internal||{};this.vj.internal.withCredentials=ca};ba.prototype.ik=function(){return this.vj&&this.vj.internal?this.vj.internal.withCredentials:null};ba.prototype.getFileData=function(){return Promise.reject()};return ba}();Object(xa.a)(h);Object(n.a)(h);Object(n.b)(h);ta["default"]=
h},598:function(xa,ta,h){var ra=h(0),na=h(3),oa=h(34),ja=h(53),ka=h(216),fa=h(99),x=function(){function r(n,f,a,b,e,w){void 0===a&&(a=null);void 0===b&&(b=null);void 0===e&&(e=null);void 0===w&&(w=null);this.mT=!1;this.Qh=0;this.FD=8;this.Cba=3E3;this.RM=!1;this.w2=this.DKa(n);this.url=f?this.w2+"/"+f:this.w2+"/ws";this.QQ=a;this.VD=b;this.EB=e;this.oba=w}r.prototype.DKa=function(n){var f=n.indexOf("://"),a="ws://";0>f?f=0:(5===f&&(a="wss://"),f+=3);var b=n.lastIndexOf("/");0>b&&(b=n.length);return a+
n.slice(f,b)};r.prototype.send=function(n){this.Js.readyState===WebSocket.CLOSED||this.mT||this.Js.send(JSON.stringify(n))};r.prototype.EK=function(){return Object(ra.b)(this,void 0,void 0,function(){var n,f=this;return Object(ra.d)(this,function(){n=Object(ja.a)("wvsQueryParameters");n.bcid=Object(oa.l)(8);Object(ja.b)("wvsQueryParameters",n);return[2,new Promise(function(a,b){var e=Object(ka.a)(f.url);f.RM=!1;f.Js=new WebSocket(e);f.Js.onopen=function(){f.mT=!1;f.Qh=0;f.VD&&f.VD();a()};f.Js.onerror=
function(){f.mT=!0};f.Js.onclose=function(w){w=w.code;f.EB&&f.EB();1E3!==w&&3E3!==w&&f.bxa(w,a,b)};f.Js.onmessage=function(w){w&&w.data&&(w=JSON.parse(w.data),w.hb?f.send({hb:!0}):w.end?close():f.QQ(w))}})]})})};r.prototype.bxa=function(n,f,a){Object(ra.b)(this,void 0,void 0,function(){var b=this;return Object(ra.d)(this,function(){if(this.RM)return f(),[2];this.Qh<this.FD?setTimeout(function(){b.RM?f():(b.Qh++,Object(na.j)("Failed to connect to server with WebSocket close code "+n+". Reconnecting to WebViewer Server, attempt "+
b.Qh+" of "+b.FD+" ..."),b.EK().then(f).catch(a))},this.Cba):a(fa.a);return[2]})})};r.prototype.bu=function(){var n;void 0===n&&(n=!1);this.Qh=0;this.RM=!0;n?this.Js.close(3E3):this.Js.close();return Promise.resolve()};return r}(),y=function(){function r(n,f,a,b,e,w,ba){void 0===b&&(b=null);void 0===e&&(e=null);void 0===w&&(w=null);void 0===ba&&(ba=null);this.Qh=this.eM=this.id=0;this.ZC=!1;this.request=null;this.FD=8;this.Cba=3E3;n=this.NCa(n);this.url=f?n+"/"+f+"pf":n+"/pf";this.kN=a;this.QQ=b;
this.VD=e;this.EB=w;this.oba=ba}r.prototype.NCa=function(n){var f=n.lastIndexOf("/");0>f&&(f=n.length);return n.slice(0,f)};r.prototype.Koa=function(n){n=n.split("\n");for(n[n.length-1]&&n.pop();0<n.length&&3>n[n.length-1].length;)"]"===n.pop()&&(this.id=0);0<n.length&&3>n[0].length&&n.shift();for(var f=0;f<n.length;++f)n[f].endsWith(",")&&(n[f]=n[f].substr(0,n[f].length-1));return n};r.prototype.Bba=function(){return Object(ra.b)(this,void 0,void 0,function(){var n=this;return Object(ra.d)(this,
function(f){switch(f.label){case 0:return this.Qh++<this.FD?[4,new Promise(function(a){return setTimeout(function(){n.oba();n.EK();a()},3E3)})]:[3,2];case 1:f.aa(),f.label=2;case 2:return[2]}})})};r.prototype.PCa=function(n){Object(ra.b)(this,void 0,void 0,function(){var f,a;return Object(ra.d)(this,function(b){switch(b.label){case 0:f=null,a=0,b.label=1;case 1:if(!(a<n.length))return[3,6];f=JSON.parse(n[a]);if(!f)return[3,5];if(!f.end)return[3,2];close();return[3,5];case 2:if(!f.id||Number(f.id)===
this.id)return[3,4];Object(na.j)("Reconnecting, new server detected");this.bu();return[4,this.Bba()];case 3:return b.aa(),[3,5];case 4:f.hb&&Number(f.id)===this.id?this.send({hb:!0}):this.ZC||this.QQ(f),b.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};r.prototype.UAa=function(n){Object(ra.b)(this,void 0,void 0,function(){var f,a,b;return Object(ra.d)(this,function(e){switch(e.label){case 0:if(!(3<=n.readyState))return[3,2];try{f=n.responseText.length}catch(w){return Object(na.h)("caught exception"),
[2]}if(0<f)try{a=this.Koa(n.responseText),0===this.id&&0<a.length&&(b=JSON.parse(a.shift()),this.id=b.id,this.Qh=0),this.PCa(a)}catch(w){}return this.ZC?[3,2]:[4,this.f5()];case 1:e.aa(),e.label=2;case 2:return[2]}})})};r.prototype.f5=function(){return Object(ra.b)(this,void 0,void 0,function(){var n=this;return Object(ra.d)(this,function(){return[2,new Promise(function(f,a){function b(){return Object(ra.b)(n,void 0,void 0,function(){return Object(ra.d)(this,function(w){switch(w.label){case 0:a(),
this.bu(),w.label=1;case 1:return this.ZC&&this.Qh<this.FD?[4,this.Bba()]:[3,3];case 2:return w.aa(),[3,1];case 3:return[2]}})})}n.request=new XMLHttpRequest;n.request.withCredentials=n.kN;var e=Object(ka.a)(n.url,0!==n.id?{id:String(n.id),uc:String(n.eM)}:{uc:String(n.eM)});n.eM++;n.request.open("GET",e,!0);n.request.setRequestHeader("Cache-Control","no-cache");n.request.setRequestHeader("X-Requested-With","XMLHttpRequest");n.request.onreadystatechange=function(){n.UAa(n.request)};n.request.addEventListener("error",
b);n.request.addEventListener("timeout",b);n.request.addEventListener("load",function(){n.VD&&n.VD();f()});n.request.send()})]})})};r.prototype.EK=function(){var n=Object(ja.a)("wvsQueryParameters");n.bcid=Object(oa.l)(8);Object(ja.b)("wvsQueryParameters",n);this.eM=this.id=0;this.ZC=!1;return this.f5()};r.prototype.send=function(n){var f=this,a=new XMLHttpRequest;a.withCredentials=this.kN;var b=Object(ka.a)(this.url,{id:String(this.id)}),e=new FormData;e.append("data",JSON.stringify(n));a.addEventListener("error",
function(){f.bu()});a.open("POST",b);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(e)};r.prototype.bu=function(){this.id=0;this.ZC=!0;this.EB&&this.EB();this.request.abort();return Promise.resolve()};return r}();xa=function(){function r(n,f,a){this.p3=n;this.target=f;this.kN=a}r.prototype.eta=function(n,f,a,b,e){void 0===n&&(n=!0);void 0===f&&(f=null);void 0===a&&(a=null);void 0===b&&(b=null);void 0===e&&(e=null);return n?new x(this.p3,this.target,f,a,b,e):new y(this.p3,this.target,
this.kN,f,a,b,e)};return r}();ta.a=xa}}]);}).call(this || window)
